export const CITIES = [
    // Standard List
    "Bengaluru",
    "Delhi",
    "Mumbai",
    "Hyderabad",
    "Pune",
    "Chennai",
    "Gurugram",
    "Noida",
    "Greater Noida",
    "Ahmedabad",
    "Jaipur",
    "Chandigarh",
    "Indore",
    "Surat",
    "Kochi",

    // 🥈 Tier-2 High Growth (Best ROI cities)
    "Nagpur",
    "Bhopal",
    "Lucknow",
    "Kanpur",
    "Agra",
    "Meerut",
    "Ghaziabad",
    "Faridabad",
    "Panipat",
    "Sonipat",
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Dehradun",
    "Haridwar",
    "Roorkee",
    "Udaipur",
    "Kota",
    "Alwar",
    "Ajmer",

    // 🥉 Tier-2 / Tier-3 Youth Dense (Underrated Gym Gold)
    "Gwalior",
    "Jabalpur",
    "Rewa",
    "Satna",
    "Sagar",
    "Raipur",
    "Bilaspur",
    "Durg",
    "Bhilai",
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Patna",
    "Muzaffarpur",
    "Gaya",
    "Bhagalpur",

    // 🌆 South India – Fitness-aware Youth
    "Coimbatore",
    "Tiruppur",
    "Madurai",
    "Salem",
    "Trichy",
    "Vellore",
    "Tirunelveli",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Tirupati",
    "Visakhapatnam",
    "Kakinada",
    "Rajahmundry",
    "Warangal",
    "Karimnagar",
    "Nizamabad",

    // 🌴 West & Coastal – Disposable Income + Lifestyle
    "Navi Mumbai",
    "Thane",
    "Kalyan",
    "Dombivli",
    "Vasai",
    "Virar",
    "Nashik",
    "Aurangabad",
    "Kolhapur",
    "Sangli",
    "Vadodara",
    "Rajkot",
    "Jamnagar",
    "Bhavnagar",

    // 🌱 Emerging / Future Boom Cities (Enter early)
    "Haldwani",
    "Rudrapur",
    "Siliguri",
    "Asansol",
    "Durgapur",
    "Kharagpur",
    "Berhampur",
    "Sambalpur",
    "Jharsuguda",
    "Rourkela",
    "Gorakhpur",
    "Bareilly",
    "Moradabad",
    "Aligarh",
    "Mathura",
    "Ayodhya"
];

export const CITY_CATEGORIES = {
    "Tier-2 High Growth": [
        "Nagpur", "Bhopal", "Lucknow", "Kanpur", "Agra", "Meerut", "Ghaziabad",
        "Faridabad", "Panipat", "Sonipat", "Ludhiana", "Amritsar", "Jalandhar",
        "Patiala", "Dehradun", "Haridwar", "Roorkee", "Udaipur", "Kota", "Alwar", "Ajmer"
    ],
    "Tier-2 / Tier-3 Youth Dense": [
        "Gwalior", "Jabalpur", "Rewa", "Satna", "Sagar", "Raipur", "Bilaspur",
        "Durg", "Bhilai", "Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Patna",
        "Muzaffarpur", "Gaya", "Bhagalpur"
    ],
    "South India – Fitness-aware Youth": [
        "Coimbatore", "Tiruppur", "Madurai", "Salem", "Trichy", "Vellore",
        "Tirunelveli", "Vijayawada", "Guntur", "Nellore", "Tirupati",
        "Visakhapatnam", "Kakinada", "Rajahmundry", "Warangal", "Karimnagar", "Nizamabad"
    ],
    "West & Coastal": [
        "Navi Mumbai", "Thane", "Kalyan", "Dombivli", "Vasai", "Virar", "Nashik",
        "Aurangabad", "Kolhapur", "Sangli", "Vadodara", "Rajkot", "Jamnagar", "Bhavnagar"
    ],
    "Emerging / Future Boom Cities": [
        "Haldwani", "Rudrapur", "Siliguri", "Asansol", "Durgapur", "Kharagpur",
        "Berhampur", "Sambalpur", "Jharsuguda", "Rourkela", "Gorakhpur", "Bareilly",
        "Moradabad", "Aligarh", "Mathura", "Ayodhya"
    ]
};

export const SEO_KEYWORDS = [
    // Primary Keywords
    "Gym Mat",
    "Gym roll",
    "Gym tile",
    "Gym Rubber Mat",
    "Gym Rubber Roll",
    "Gym Rubber Tile",
    "Fitness Flooring",
    "Gym Flooring",
    "Sports flooring",
    "Rubber Tile",
    "Rubber roll",
    "Gym turf",
    "Gym Vinyl",
    "Pvc planks",
    "LVT - laminated vinyl tiles",
    "Laminated wooden flooring",
    // Additional High-Intent Keywords
    "gym flooring manufacturer",
    "rubber flooring supplier",
    "commercial gym flooring",
    "home gym flooring",
    "gym flooring installation",
    "best gym flooring",
    "gym flooring price",
    "rubber gym mats for sale",
    "interlocking gym tiles",
    "shock absorbing gym floor",
    "heavy duty gym flooring",
    "fitness center flooring",
    "crossfit gym flooring",
    "weight room flooring",
    "gym floor covering",
    "anti slip gym flooring",
    "noise reducing gym floor",
    "eco friendly gym flooring",
    "gym flooring near me",
    "buy gym flooring online",
];

export const GYM_PRODUCTS = [
    "4mm gym roll",
    "6mm gym roll",
    "8mm Gym Roll",
    "10mm Gym roll",
    "Grey gym roll",
    "Grey gym tile",
    "Laminated Tile",
    "Interlock tile",
    "Interlock Rubber Tile",
    "Sports mat 20mm",
    "Sports mat 25mm",
    "Eva mat 20mm",
    "EVA Mat 25mm",
    "Foam tiles"
];
